### ISSUE TITLE
Stylesheets used by Transkribus

### ISSUE THREAD

**Issue by cneud** [cneud/ocr-conversion-scripts#1]
https://github.com/Transkribus/TranskribusCore/tree/master/src/main/resources/xslt

**Comment by cneud** [comment]
@mikegerber [found](https://github.com/OCR-D/ocrd_fileformat/issues/32#issuecomment-812070754) a version of this that is still being updated:
https://gitlab.com/readcoop/transkribus/TranskribusCore/-/tree/master/src/main/resources/xslt

**Comment by mikegerber** [comment]
I just checked and as `PageToAlto.xsl` doesn't mention ReadingOrder it might not be suitable.
