### ISSUE TITLE
Transformation for ImageWare MyBib

### ISSUE THREAD

**Issue by karkraeg** [cneud/ocr-conversion-scripts#4]
I wrote a conversion script to transform [ImageWare MyBib eL](https://www.imageware.de/produkte/mybib-el-allgemein/) OCR to ALTO: https://github.com/karkraeg/im2alto 

Example for ImageWare OCR: https://library.fes.de/ddb/vs07100/VS07100_1.xml

Is this of interest for this collection of conversion scripts?

**Comment by cneud** [comment]
Yes and thanks!

**Comment by kba** [comment]
Might also be a candidate for https://github.com/UB-Mannheim/ocr-fileformat @karkraeg feel free to open an issue there as well.
